Repository webriq-pagebuilder/site-template-default, pull requests merged in 2022-03, with the labels that each got.

#64 SEO Fixes
  component/SEO.js
Labels: bug

#56 Pricing variant d
  component/sections/pricing/index.js
  component/sections/pricing/variant_d.js
  lib/secureKey.js
  package.json
  pages/api/paymentIntent/index.js
  pages/api/submitForm/index.js
Labels: documentation, enhancement

#68 Show corresponding page for never published page
  pages/[slug].js
  pages/api/query.js
  pages/index.js
  pages/no-preview.js
Labels: documentation, enhancement

#75 Issue-A0A6-I10 show more form fields on preview
  component/sections/call_to_action/variant_d.js
  component/sections/hero/variant_e.js
  component/sections/sign_in_sign_up/variant_a.js
  component/sections/sign_in_sign_up/variant_b.js
Labels: documentation

#76 Issue A0A6-I11 Footer section limits
  component/sections/footer/variant_a.js
Labels: enhancement
