Repository webriq-pagebuilder/site-template-default, pull requests merged in 2024-07, with the labels that each got.

#246 Hotfix Media Browser issue
  package.json
  yarn.lock
Labels: bug

#248 Minor improvements on autologin
  pages/studio/[[...index]].tsx
Labels: bug, enhancement

#247 Refactor Autologin
  pages/studio/[[...index]].tsx
Labels: bug

#249 Release 5.2.0
  README.md
  package.json
  pages/studio/[[...index]].tsx
  yarn.lock
Labels: Minor
