Repository webriq-pagebuilder/site-template-default, pull requests merged in 2024-11, with the labels that each got.

#262 RC-6.0.3 Theme Settings bug fixes
  components/PreviewNoHomePage.tsx
  components/ThemeSettings.tsx
  components/componentsData.ts
  components/data/schemas.ts
  components/list.tsx
  components/sections/navigation/index.tsx
  components/sections/navigation/variant_a.tsx
  components/sections/navigation/variant_b.tsx
  components/sections/navigation/variant_c.tsx
  components/sections/navigation/variant_d.tsx
  components/theme-settings/BasicThemeSettings.tsx
  components/theme-settings/ColorPicker.tsx
  components/theme-settings/ConfirmThemeDialog.tsx
  components/theme-settings/SearchBar.tsx
  components/theme-settings/ToggleDarkMode.tsx
  components/theme-settings/templates/RevertAllTemplate.tsx
  components/theme-settings/templates/SaveAsTemplate.tsx
  components/theme-settings/templates/SetThemeTemplate.tsx
  components/ui/image.tsx
  components/ui/index.ts
  components/ui/link.tsx
  context/ThemeSettingsContext.tsx
  package.json
  pages/[slug].tsx
  pages/_app.tsx
  pages/index.tsx
  types.ts
  utils/theme/index.ts
  yarn.lock
Labels: bug, enhancement

#265 Release 6.0.3
  components/PreviewNoHomePage.tsx
  components/ThemeSettings.tsx
  components/common/index.ts
  components/componentsData.ts
  components/data/dynamic.ts
  components/data/schemas.ts
  components/theme-settings/BasicThemeSettings.tsx
  components/theme-settings/ColorPicker.tsx
  components/theme-settings/SearchBar.tsx
  components/theme-settings/ToggleDarkMode.tsx
  package.json
  pages/_app.tsx
  pages/api/query.ts
  pages/index.tsx
  schemas/schema.ts
  studio/components/AutologinPrepage.tsx
  studio/utils/index.ts
  utils/theme/index.ts
  yarn.lock
Labels: bug, enhancement

#267 [WIP] Fixes for Theme Settings
  components/PreviewNoHomePage.tsx
  components/ThemeSettings.tsx
  components/sections/navigation/index.tsx
  components/theme-settings/BasicThemeSettings.tsx
  components/theme-settings/ColorPicker.tsx
  components/theme-settings/SearchBar.tsx
  components/theme-settings/ToggleDarkMode.tsx
  components/theme-settings/templates/RevertAllTemplate.tsx
  components/theme-settings/templates/SaveAsTemplate.tsx
  components/theme-settings/templates/SetThemeTemplate.tsx
  package.json
  pages/[slug].tsx
  pages/_app.tsx
  pages/api/query.ts
  pages/index.tsx
  pages/theme-page/index.tsx
  public/robots.txt
  schemas/documents/themePage.ts
  schemas/schema.ts
  scripts/templates/components/index.tsx.hbs
  scripts/templates/components/{{variantName}}.tsx.hbs
  studio/components/AutologinPrepage.tsx
  studio/documentActions/index.ts
  studio/resolvePreviewUrl.ts
  utils/theme/index.ts
  yarn.lock
Labels: bug, enhancement, Minor

#268 Dynamic Components | Theme Settings | Component files Update
  components/PreviewNoHomePage.tsx
  components/ThemeSettings.tsx
  components/common/index.ts
  components/sections/navigation/index.tsx
  components/theme-settings/BasicThemeSettings.tsx
  components/theme-settings/ColorPicker.tsx
  components/theme-settings/templates/RevertAllTemplate.tsx
  components/theme-settings/templates/SaveAsTemplate.tsx
  components/theme-settings/templates/SetThemeTemplate.tsx
  package.json
  pages/[slug].tsx
  pages/api/query.ts
  pages/index.tsx
  pages/theme-page/index.tsx
  public/robots.txt
  schemas/documents/themePage.ts
  schemas/schema.ts
  studio/documentActions/index.ts
  studio/resolvePreviewUrl.ts
  yarn.lock
Labels: bug, enhancement, Minor

#272 Hotfix: Theme Settings not loaded
  components/ThemeSettings.tsx
Labels: bug

#273 Hotfix navigation component not visible
  components/sections/navigation/index.tsx
Labels: bug

#274 Hotfix: Links not working
  components/ui/link.tsx
Labels: bug, Minor

#275 Updates and Fixes for StackShift v6
  components/ThemeSettings.tsx
  components/theme-settings/BasicThemeSettings.tsx
  components/theme-settings/ColorPicker.tsx
  components/theme-settings/SelectSettings.tsx
  components/theme-settings/ToggleDarkMode.tsx
  components/theme-settings/defaultThemeConfig.ts
  package.json
  sanity.config.ts
  schemas/documents/pages.ts
  schemas/schema.ts
  yarn.lock
Labels: enhancement, Minor
