Repository webriq-pagebuilder/site-template-default, pull requests merged in 2025-03, with the labels that each got.

#281 UI fixes for components - Social Feed, Pricing, Product Info, FAQ, Features, Portfolio and How it works
  components/ecwid/AddToBag.tsx
  components/ecwid/AddToWishlist.tsx
  components/page/index.tsx
  components/sections/pages_productInfo/variant_a.tsx
  components/sections/pages_productInfo/variant_b.tsx
  components/sections/pricing/variant_b.tsx
  components/sections/pricing/variant_d.tsx
  components/sections/social_media_feed/index.tsx
  components/sections/social_media_feed/variant_a.tsx
  components/sections/social_media_feed/variant_b.tsx
  context/SocialMediaFeedContext.tsx
  package.json
  pages/api/query.ts
  schemas/documents/pages.ts
  schemas/schema.ts
  types.ts
  yarn.lock
Labels: Enhancement, Minor, StackShift v6

#279 Fixes for Storybook
  .github/workflows/chromatic.yml
  .storybook/main.ts
  components/Storybook.mdx
  components/common/index.ts
  components/sections/all_products/stories/all_products.stories.tsx
  components/sections/featured_products/stories/featured_products.stories.tsx
  components/sections/pages_productInfo/stories/page_productInfo.stories.tsx
  components/sections/pricing/stories/pricing.stories.tsx
  components/sections/product_info/stories/product_info.stories.tsx
  components/sections/wishlist/stories/wishlist.stories.tsx
  components/stories/all_products.dynamic.tsx
  components/stories/app_promo.dynamic.tsx
  components/stories/blog.dynamic.tsx
  components/stories/call_to_action.dynamic.tsx
  components/stories/contact.dynamic.tsx
  components/stories/faqs.dynamic.tsx
  components/stories/featured_products.dynamic.tsx
  components/stories/features.dynamic.tsx
  components/stories/footer.dynamic.tsx
  components/stories/header.dynamic.tsx
  components/stories/how_it_works.dynamic.tsx
  components/stories/logoCloud.dynamic.tsx
  components/stories/navigation.dynamic.tsx
  components/stories/newsletter.dynamic.tsx
  components/stories/page_productInfo.dynamic.tsx
  components/stories/portfolio.dynamic.tsx
  components/stories/pricing.dynamic.tsx
  components/stories/product_info.dynamic.tsx
  components/stories/sign_in_sign_up.dynamic.tsx
  components/stories/stats.dynamic.tsx
  components/stories/team.dynamic.tsx
  components/stories/testimonials.dynamic.tsx
  components/stories/text_component.dynamic.tsx
  helper/defaultValues.ts
  package.json
  schemas/schema.ts
  utils/schemas.ts
  yarn.lock
Labels: Bug, Enhancement, Minor, StackShift v6

#270 Automated Component Creation
  package.json
  plopfile.mjs
  scripts/templates/component.tsx.hbs
  yarn.lock
Labels: Enhancement, Minor, StackShift v6

#280 Run playwright and chromatic tests for master branch
  .github/workflows/chromatic.yml
  .github/workflows/playwright.yml
Labels: Bug, Minor, StackShift v6

#285 RC608-Hot fixes for issues found during QA/QC
  components/common/index.ts
  package.json
  yarn.lock
Labels: Bug, Enhancement, Patch, StackShift v6
